### ISSUE TITLE
Support .save() for framebuffers

### ISSUE THREAD

**Issue by davepagurek** [davepagurek/p5.Framebuffer#23]
Example code to do this from outside the library:

```js
let img = createImage(fbo.width, fbo.height);
img.loadPixels();      
var gl = fbo._renderer.GL;
var framebuffer = gl.createFramebuffer();
gl.bindFramebuffer(gl.FRAMEBUFFER, framebuffer);
gl.framebufferTexture2D(gl.FRAMEBUFFER, gl.COLOR_ATTACHMENT0, gl.TEXTURE_2D, fbo.colorTexture, 0);
if (gl.checkFramebufferStatus(gl.FRAMEBUFFER) == gl.FRAMEBUFFER_COMPLETE) 
{
    gl.readPixels(0, 0, fbo.width, fbo.height, gl.RGBA, gl.UNSIGNED_BYTE, img.pixels);
}
gl.bindFramebuffer(gl.FRAMEBUFFER, null);
img.updatePixels();
save(img, "image",".png")
```

**Comment by davepagurek** [comment]
or alternatively: `toImage`

**Comment by ofZach** [comment]
heavy support for this, or something like a "readToPixels()" function that could be chained to a saving operation -- here's a suggestion I made for another library

https://github.com/aferriss/p5Fbo/issues/3

**Comment by davepagurek** [comment]
Sounds good! This issue https://github.com/processing/p5.js/issues/6082 is probably the next one I'll work on for p5's upcoming Framebuffer support, I'm hoping to get support for something like this into p5 🙂

**Comment by davepagurek** [comment]
I've got a PR up for this in p5 now! https://github.com/processing/p5.js/pull/6109 I'm aiming to have all this ready to go in the next p5 release.

**Comment by davepagurek** [comment]
Merged in now! This will be a feature in the next version of p5 without needing this library for it 🙂 I'll update this library to just be a place for the custom renderers and add a readme section about migrating.
